project:
  type: website
  output-dir: docs

website:
  title: "sophia-brown.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - href: about.qmd
        text: Home
      - dashboard.qmd
        
format:
  html:
    theme: 
     light: vapor
     dark: cosmo
    css: styles.css
    toc: true

editor: visual

