knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
project:
  type: website
  output-dir: docs

website:
  title: "sophia-brown.github.io"
  navbar:
    left:
    - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - resume.qmd
      - about.qmd
      - icon: github
        href: http://github.com/sophia-brown
        target: blank

      
format:
  html:
    theme: 
     light: vapor
     dark: cosmo
    css: styles.css
    toc: true

editor: visual

