project:
  type: website
  output-dir: docs

website:
  title: "sophia-brown.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - href: about.qmd
        text: Home
      - dashboard.qmd
  page-footer:
    left: Â© Copyright 2025, Sophia Brown
    right: This website is built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}
        
format:
  html:
    theme: 
     light: vapor
     dark: cosmo
    css: styles.css
    toc: true


editor: visual

